[package]
name = "flatten_files"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.37"
clipboard = "0.5.0"
rayon = "1.10.0"
walkdir = "2.5.0"
